#
# TODO: create rake install to promt users for these items
#

development:
  adapter: mysql
  database: lepilo_dev
  username: root
  password: 

production:
  adapter: mysql
  database: lepilo_prod
  username: root
  password: 

test:
  adapter: mysql
  database: lepilo_test
  username: root
  password: 
