# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "articles", :force => true do |t|
    t.column "topic_id",     :integer
    t.column "thumbnail_id", :integer
    t.column "released",     :boolean
    t.column "release_date", :date
    t.column "user_id",      :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "reference",    :string,   :limit => 25
    t.column "type",         :string,   :limit => 25
    t.column "title",        :string,   :limit => 250
    t.column "description",  :text
  end

  create_table "articles_tags", :id => false, :force => true do |t|
    t.column "article_id", :integer
    t.column "tag_id",     :integer
  end

  create_table "block_links", :force => true do |t|
    t.column "linked_id",     :integer
    t.column "linked_type",   :string,  :limit => 36
    t.column "position",      :integer
    t.column "fragment_id",   :integer
    t.column "collection_id", :integer
  end

  create_table "collections", :force => true do |t|
    t.column "topic_id",     :integer
    t.column "thumbnail_id", :integer
    t.column "released",     :boolean
    t.column "user_id",      :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "title",        :string,   :limit => 250
    t.column "description",  :text
  end

  create_table "fragments", :force => true do |t|
    t.column "article_id",  :integer
    t.column "content",     :string,   :limit => 64
    t.column "position",    :integer
    t.column "user_id",     :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "info",        :string,   :limit => 250
    t.column "fragment_id", :integer
  end

  create_table "mediablocks", :force => true do |t|
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "uploaded_at",   :datetime
    t.column "original_name", :string
    t.column "content_type",  :string,   :limit => 100
    t.column "filename",      :string
    t.column "thumbnail",     :string
    t.column "original",      :string
    t.column "title",         :string
    t.column "description",   :string
  end

  create_table "settings", :force => true do |t|
    t.column "setting_id",  :integer, :default => 0
    t.column "position",    :integer
    t.column "key",         :string
    t.column "value",       :string
    t.column "description", :text
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string, :limit => 250
  end

  create_table "textblocks", :force => true do |t|
    t.column "user_id",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "title",      :string,   :limit => 250
    t.column "content",    :text
  end

  create_table "topics", :force => true do |t|
    t.column "topic_id",    :integer
    t.column "position",    :integer
    t.column "title",       :string,  :limit => 250
    t.column "description", :text
    t.column "permalink",   :string
  end

  create_table "users", :force => true do |t|
    t.column "created_at",                :datetime
    t.column "login",                     :string,   :limit => 80
    t.column "password",                  :string,   :limit => 40
    t.column "role",                      :string,   :limit => 30
    t.column "name",                      :string,   :limit => 150
    t.column "email",                     :string,   :limit => 250
    t.column "description",               :string,   :limit => 250
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "admin",                     :boolean
  end

end
